export const keywords: string[] = [
  // Brand & Platform
  "infinity list",
  "discord bot list",
  "discord server list",
  "discord template list",
  "discord bots directory",
  "discord servers directory",
  "top discord bots",
  "top discord servers",
  "best discord bots",
  "best discord servers",
  "verified discord bots",
  "featured discord servers",

  // Bot Related
  "discord bot",
  "music bot",
  "moderation bot",
  "utility bot",
  "gaming bot",
  "leveling bot",
  "economy bot",
  "fun bot",
  "automod bot",
  "welcome bot",
  "custom bot",
  "verification bot",
  "discord bot features",
  "discord bot commands",
  "discord bot dashboard",
  "bot development",
  "bot hosting",
  "bot verification",
  "bot analytics",
  "bot management",

  // Server Related
  "discord server",
  "gaming server",
  "community server",
  "nft server",
  "crypto server",
  "anime server",
  "music server",
  "art server",
  "roleplay server",
  "dating server",
  "partnership server",
  "advertising server",
  "emote server",
  "giveaway server",
  "streaming server",
  "server features",
  "server rules",
  "server roles",
  "server customization",
  "server management",

  // Templates
  "discord template",
  "server template",
  "gaming template",
  "community template",
  "roleplay template",
  "school template",
  "business template",
  "esports template",
  "clan template",
  "streaming template",
  "template customization",
  "template setup",
  "template features",
  "template themes",
  "template categories",

  // Features & Categories
  "bot commands",
  "server features",
  "template features",
  "bot categories",
  "server categories",
  "template categories",
  "server discovery",
  "bot discovery",
  "server tags",
  "bot tags",
  "server search",
  "bot search",
  "server listing",
  "bot listing",
  "server promotion",
  "bot promotion",

  // Community & Support
  "discord community",
  "bot support",
  "server support",
  "bot documentation",
  "server guide",
  "template guide",
  "bot reviews",
  "server reviews",
  "bot ratings",
  "server ratings",
  "discord resources",
  "community tools",
  "discord utilities",
  "server growth",
  "bot development"
];
